DEEPSPEED_TIMEOUT=120 deepspeed --num_gpus 8 --master_port=19901 src/train.py \
    --deepspeed ds_config/ds_config_3.json \
    --stage sft \
    --model_name_or_path "/mnt/tenant-home_speed/xz/opsfm-xz/sft_checkpoint/xz/qwen2.5-ts-sp-stage1-1119/checkpoint-400" \
    --dataset "chatts_dev" \
    --interleave_probs "1.0" \
    --do_train \
    --mix_strategy "interleave_over" \
    --template "qwen"  \
    --finetuning_type full \
    --output_dir "/mnt/tenant-home_speed/xz/sft_checkpoint/qwen2.5-ts-sp-chatts-dev" \
    --overwrite_output_dir \
    --per_device_train_batch_size 2 \
    --gradient_accumulation_steps 32 \
    --lr_scheduler_type cosine \
    --logging_steps 1 \
    --save_steps 200 \
    --learning_rate 1e-5 \
    --warmup_ratio 0.02 \
    --num_train_epochs 0 \
    --max_steps 1000 \
    --plot_loss \
    --fp16 \
    --save_only_model \
    --save_safetensors False \
    --preprocessing_num_workers 96 \
    --ts_inputs \
    --freeze_ts_encoder False \
    --cutoff_len 3000
