NCCL_DEBUG=WARN DEEPSPEED_TIMEOUT=120 deepspeed --num_gpus 8 --master_port=19901 src/train.py \
    --deepspeed ds_config/ds_config_3.json \
    --stage sft \
    --model_name_or_path "[PATH_TO_CHATTS]" \
    --dataset "[DATASET_NAMES]" \
    --interleave_probs "1.0" \
    --do_train \
    --mix_strategy "interleave_over" \
    --template "chatts"  \
    --finetuning_type lora \
    --lora_rank 8 \
    --lora_target "q_proj,k_proj,v_proj" \
    --output_dir "[OUTPUT_PATH]" \
    --overwrite_output_dir \
    --per_device_train_batch_size 2 \
    --gradient_accumulation_steps 32 \
    --lr_scheduler_type cosine \
    --logging_steps 1 \
    --save_steps 100 \
    --learning_rate 1e-5 \
    --timeseries_sft_lr 1e-5 \
    --warmup_ratio 0.02 \
    --num_train_epochs 0 \
    --max_steps 600 \
    --plot_loss \
    --fp16 \
    --save_only_model \
    --save_safetensors False \
    --preprocessing_num_workers 96 \
    --trust_remote_code True \
    --cutoff_len 4000